### ISSUE TITLE
Nice to Haves

### ISSUE THREAD

**Issue by ZurielRedux** [Steel-Dev/BetterNetherite#3]
Just installed the plugin and I love it so far. We are running a bit of a slower progression server so we were wondering if you could add an option to use netherite blocks for the upgrades instead of bars. 

Also, any chance you could make it so you could do all tool upgrades this way? it would give village trades like enchanted iron more value if they could be upgraded to diamond some how. I realize this is a bit out of scope, but I thought I would ask.

**Comment by Steel-Dev** [comment]
I'm glad you like it, but please don't use the issue tracker for suggestions - join the [discord](https://discord.gg/t3PHeNb) for that! :p
