### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by TheGam1ngWizard** [Steel-Dev/BetterNetherite#4]
Mobs spawn uncontrollably in the nether (a single clear betternetherite mobs command cleared 1500+ mobs).

Mobs have a bad tendency to follow players through the portal and kill them while they are loading the overworld.

No way to set per-player spawn limits and cannot change chance/frequency of spawns.

If we could have a betternetherite mob-cap limit, and a way to lower the frequency of mobs (other than just turning them on and off) that would do a lot to make it more fun/usable.

**Comment by Steel-Dev** [comment]
Thank you for your report! I will get onto fixing this soon. I apologize for any inconvenience this may have caused.
I will add a mob-cap, along with the ability to lower the frequency per-mob.
Thanks again! I'll keep this open, and close it when I get this fixed. Have a good night!

**Comment by Steel-Dev** [comment]
Hello, I have fixed the issues you have reported - hopefully - here is a preview version of 1.0.7, let me know if the issues persist, and if the fixes are good for you. (there is also some new things in this update unrelated to this issue you can have a preview of for your troubles :p)
If everything is all good, I will be pushing the update out on spigot with a little more.
[BetterNetherite-1.0.7.zip](https://github.com/Steel-Dev/BetterNetherite/files/5433938/BetterNetherite-1.0.7.zip)
