### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by TheGam1ngWizard** [Steel-Dev/BetterNetherite#5]
<img width="1070" alt="berror" src="https://user-images.githubusercontent.com/55005148/97091982-ec503f00-160d-11eb-801d-d50cf9e3e0a2.png">

**Comment by Steel-Dev** [comment]
Thanks again for your report! I must've overlooked something here, I'll get that fixed for the next update!

**Comment by Steel-Dev** [comment]
This issue has been resolved and fixed. The fix will be out in the next update (1.0.7). Thanks again for your report! And thanks for enjoying my plugin!
