### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by squeaky2137** [Steel-Dev/BetterNetherite#6]
**Describe the bug**
The plugin is saying dull plugin is not enabled

**To Reproduce**
Finished configs and did everything right and restarted server multiple times

**Expected behavior**
For the plugin to work and be able to use smithing table.

**Plugin Version**
1.16

**Server Version**
Spigot
![5064080C-7B62-483E-BF65-B4B4C32BB7C5](https://user-images.githubusercontent.com/73867896/97949322-d9014a00-1d58-11eb-86e4-28749c469a62.jpeg)

**Comment by Steel-Dev** [comment]
Can you please provide any additional information? I can't do anything with this. Were there any issues when the plugin was being loaded? I've run many tests and had many people test it, and they haven't run into this.
Seems like it's on your end, but just in case, please provide any additional information so I can fix the issue if the plugin is at fault.

**Comment by Steel-Dev** [comment]
Also, You provided the incorrect information for the Plugin Version and Server Version.
The plugin version, as seen in your screenshot, is 1.0.8.

Server version, I have no clue, you said 1.16 spigot, but the plugin was developed for 1.16.3 (soon updating to 1.16.4)
Please be more specific.

**Comment by squeaky2137** [comment]
Sorry, and maybe I did the config wrong or miss deleted someone thing so here is the config.
![6580EC59-4B61-4707-B3A6-04919DC912AC](https://user-images.githubusercontent.com/73867896/98013472-07fed680-1dc0-11eb-8d6f-f3eaa5dc528f.jpeg)
![35E07283-7F52-458C-90FF-9028E0DDD759](https://user-images.githubusercontent.com/73867896/98013480-09300380-1dc0-11eb-8333-51ef4f139130.jpeg)
![2A4C3E3C-B6BE-4C6C-887C-A9899F83ED6D](https://user-images.githubusercontent.com/73867896/98013481-0a613080-1dc0-11eb-8129-451e40ce166b.jpeg)
![6A656E7B-CB61-4258-8B3D-2755D4676E54](https://user-images.githubusercontent.com/73867896/98013483-0a613080-1dc0-11eb-9fed-9ecb306defb8.png)

**Comment by Steel-Dev** [comment]
All good - The config looks fine, are there any errors in the console at all when the plugin loads?

**Comment by squeaky2137** [comment]
Here is all it says when I try doing a command but I will reload plugin and also see if it shows errors.
![DC7DDB31-43E7-4CF0-877D-09A9CAE0062A](https://user-images.githubusercontent.com/73867896/98014777-ad667a00-1dc1-11eb-914f-0335f88e8246.jpeg)
![D1375431-199E-44A3-AD91-AAD3D8B663F1](https://user-images.githubusercontent.com/73867896/98014786-af303d80-1dc1-11eb-906e-ef83fd75601e.png)
![3537AF1A-2ED6-4190-9BA1-6FF7F4A1B02F](https://user-images.githubusercontent.com/73867896/98014789-afc8d400-1dc1-11eb-9ac7-ded01934c1ea.jpeg)

**Comment by squeaky2137** [comment]
Here is its start up error.
![832DEFF8-8327-49E4-9B74-C46668D67665](https://user-images.githubusercontent.com/73867896/98015941-fa971b80-1dc2-11eb-9287-769c02552f3e.jpeg)
![5DE09B64-5A7C-43EF-9C16-A1A75EF438A6](https://user-images.githubusercontent.com/73867896/98015943-fc60df00-1dc2-11eb-96fd-f83bc0583201.jpeg)
![FBEF9162-6924-4E2C-948E-E18605C14985](https://user-images.githubusercontent.com/73867896/98015947-fcf97580-1dc2-11eb-8c9a-6148e023c436.png)

**Comment by Steel-Dev** [comment]
Oh, the plugin won't function properly on 1.16.4 yet as the NBTAPI I'm using for it doesn't support it just yet. I apologize for this, there's not much I can do about it!

I will update you, and push out an update to the plugin when the API supports 1.16.4.

I assume you're running 1.16.4? Because it says so in the errors. But you said you're on 1.16.3. Which one is it?

**Comment by squeaky2137** [comment]
Oh ya I’m 1.16.4 sorry well ok thanks for the help :)

**Comment by Steel-Dev** [comment]
Hello! I'm letting you know that I've added 1.16.4 support, and it is now functional! Download it [here](https://www.spigotmc.org/resources/better-netherite.84526/)!
Thanks!

**Comment by squeaky2137** [comment]
Yay thank you I will add it tomorrow! 👍
