### ISSUE TITLE
[REQUEST]

### ISSUE THREAD

**Issue by squeaky2137** [Steel-Dev/BetterNetherite#7]
**What is your suggestion?**
My suggestion is for you to either make another plugin or add to this plugin (which probs would be easier) a feature where if you put a netherite ingot in your crafting table with a diamond tool you can turn it into a netherite tool with the same enchants like how it was in beta. I know this is easy to code ( pretty sure at least ) but I can’t do it as I don’t have a pc yet. I would love if you added this or made another plugin but if you don’t it’s fine. 

**Why are you suggesting it?**
I’m using geyser where smithing tables haven’t been fixed / added so I tried your plugin but it didn’t fix it as it’s an inventory issue they are working on. I don’t have a pc either so I can’t code this myself.

**Do you think others would like this suggestion? If so, why do you think?**
Yes, there isn’t a single plugin that can fix this and so anyone with geyser would love this fix and would use it.

**How do you think this suggestion would improve the plugin?**
It would probably get a lot of people to use this plugin to fix netherite for geyser plus shrines etc are amazing.

Thank you for looking at this and hope you accept it :)!

**Comment by Steel-Dev** [comment]
Hey! thanks for your request! I like the idea, and I'll get on it soon, hopefully. I'm currently sick, though :c

**Comment by squeaky2137** [comment]
Thank you for reading this and going to add it!!! It should be quick to add too! So sorry you’re sick hope you get better soon :( wish you the best of luck! Make sure to get better!

**Comment by Steel-Dev** [comment]
Thanks! Have a wonderful day/night :p I'll try my best to get better haha
I'll leave this open so I can notify you when I add this feature.

**Comment by squeaky2137** [comment]
Thank you and have a great rest of your day/nigh to you too! Also your a great dev not only adding features and updating but responding to people and being friendly! Love your work and keep it up!!! Also if you ever want a discord server hmu I’ll make you one! Hope you get better !!!

**Comment by Steel-Dev** [comment]
I try my best! I've been thinking about a discord server at one point, I'll let you know!

**Comment by Steel-Dev** [comment]
Hey! Just updating you - I've thought of an idea for this request.
Instead, it will be done using an 'Upgrade Pack' which is craftable. Upon right-clicking an item in your inventory with this pack, it will upgrade the item to Netherite and will damage the pack.
Thought this was a unique idea, wanted your input since it is your suggestion! :D

**Comment by Steel-Dev** [comment]
[Here](https://imgur.com/j98gnQD) is my idea in action, hope you like it!

**Comment by squeaky2137** [comment]
Amazing idea! Love the concept and how unique it is. It looks super cool and I think not only my server but any server would like this concept. This also eliminates the possible issue where you when you used a crafting table it might not give you the netherite item since the reason smithing tables don’t work is inventory problem. This is amazing and love your work keep it up!!
Only problem with this which probably won’t come up is mobile / iPad can’t right click but if they move an item into another slot normally it works so when you release it I’ll test on mobile.

**Comment by Steel-Dev** [comment]
Didn't even know you could run plugins on mobile. But I'm glad you like it, releasing soon.

**Comment by squeaky2137** [comment]
Ok great! And to run plugins on mobile you use a java server then use a plugin that creates a proxy so bedrock can join java servers

**Comment by Steel-Dev** [comment]
Ah, I see, well sadly, I'm unsure if it will work, let me know if it does, if not I'm sorry, nothing I can do since I know nothing about mobile.

Anyways, an update with this new feature has been posted! Thank you for the suggestion.

**Comment by squeaky2137** [comment]
![CE365E71-C19E-4B22-B283-A2E12E33707D](https://user-images.githubusercontent.com/73867896/98762227-d2985100-239c-11eb-91a7-f8ec18dba1ca.png)
Ummm it’s the newest version? And my server is 1.16.4

**Comment by Steel-Dev** [comment]
Ope, this was my bad, I'll push a hotfix for Monstrorvm.

**Comment by Steel-Dev** [comment]
I've pushed the hotfix that caused that error, let me know if it's been resolved. 
I greatly apologize for this, I am still sick haha
Thanks for letting me know!

**Comment by squeaky2137** [comment]
It sadly doesn’t work but! I know a way to fix it. On mobile in the chest gui area you can right click items you by moving them as shown in the video. So a fix is you could add a custom cmd like /ntable where you put the pack in one slot and the sword in another then you click a button and it turns the sword / item into netherite kinda like a custom anvil ( or you can just make it work in anvil) I will show below how it can work and how it doesn’t in the video. https://imgur.com/a/w7W07yZ Take your time as you need as I know you are sick. I know this is possible but don’t know how easy Xd. Good luck and it’s ok if you don’t want to do this. Take your time too if needed.

**Comment by Steel-Dev** [comment]
Wow, that's actually really cool you can play with it on Mobile. I'll try my best to do something like that for you, I do want to because I want everyone to have the best experience!

**Comment by squeaky2137** [comment]
Thanks! You’re a great dev! If you need help in how it could work I can show you a design in action using cmd blocks in a bedrock world

**Comment by Steel-Dev** [comment]
Thank you so much!
I've hacked together a simple concept I'm gonna refine in a bit here.
Is [this](https://i.imgur.com/yuR5Km8.gif) what you want?

**Comment by squeaky2137** [comment]
I totally forgot you could just code it into an anvil Xd. That’s even better then what I was thinking and wanted it’s amazing! Great work and yes it’s what I wanted Xd! Thank you so much!!!

**Comment by Steel-Dev** [comment]
ahahha, well no problem! I will be releasing it soon, I'm working a bit slow since the sickness is getting worse. (Not covid, don't worry! haha)

**Comment by squeaky2137** [comment]
That’s great you don’t have COVID! I don’t mind you working slow because of a sickness lol I wouldn’t even care if you didn’t work cause of it but thank you for working and great job! Hope you get better!

**Comment by Steel-Dev** [comment]
yeah :p thanks!

**Comment by squeaky2137** [comment]
You still sick? If so that’s horrible get better!

**Comment by Steel-Dev** [comment]
I've been recovering, and I've been busy with other things, I'm pushing out the new feature to BN soon, though!

**Comment by squeaky2137** [comment]
Ok and it’s fine I understand if you are busy

**Comment by Steel-Dev** [comment]
I just pushed it out! Lemme know if it works alright for ya!

**Comment by squeaky2137** [comment]
Ok lemme install it

**Comment by squeaky2137** [comment]
It doesn’t work unless you need the texture pack but it’s fine you don’t need to keep working on it if you don’t want to Xd unless your super bored lol. You’ve been working hard your fine if you don’t wanna Xd. Also what you can do if you do wanna continue is make a cmd that when you open there is 3 slots you put the pack in 2 and sword in 1 then click / move green wool or glass pane and it turns into netherite item but thank you for working so hard!

**Comment by Steel-Dev** [comment]
texture pack isnt needed, i dont understand why it wont work
