### ISSUE TITLE
[BUG] Could not pass event PlayerInteractEvent

### ISSUE THREAD

**Issue by Edrow-6** [Steel-Dev/BetterNetherite#8]
**Describe the bug**
Error in the console

**To Reproduce**
Strike an entity

**Expected behavior**
Do not have any errors

**Screenshots**
![image](https://user-images.githubusercontent.com/25459251/126623497-52cfa4c4-8947-4b96-b6a6-3a7c05ee550b.png)

**Plugin Version**
Lastest (1.1.7)

**Server Version**
1.17.1, Paper 1.17.1-116 with Java 16

**Comment by Steel-Dev** [comment]
I pushed out a hotfix the other day that should fix this, go to the spigot page and download it - let me know if it occurs again.

**Comment by Edrow-6** [comment]
it is already the last version😥

**Comment by Steel-Dev** [comment]
Can you tell me the steps to reproduce this error? I might have missed something, then. What were you doing at the time?

**Comment by Edrow-6** [comment]
Whenever an entity takes damage from a player

**Comment by Steel-Dev** [comment]
It's an interact event, not a damage event. I don't see how that would trigger it.
Try this build: https://drive.google.com/file/d/15KF6GJVdYm8-OLpsbnZ1wrVx030K3Y3a/view?usp=sharing

**Comment by Edrow-6** [comment]
Thank you very much, I no longer have the error with this version 👍

**Comment by Steel-Dev** [comment]
Great! you're welcome - and thank you very much for reporting the issue.
