### ISSUE TITLE
[BUG] Could not pass event PlayerJoinEvent/PlayerResourcePackStatusEvent

### ISSUE THREAD

**Issue by FunkyNico** [Steel-Dev/BetterNetherite#9]
**Describe the bug**
When you join the server the console gets an error.

**To Reproduce**
1. Join the server
2. Wait texture pack
3. Texture pack aplies
4. See error on console

**Expected behavior**
No error, lol.

**Plugin Version**
BetterNetherite v1.1.7

**Server Version**
Paper version git-Paper-133 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: b32a3b1)
System Info: Java 16 (OpenJDK 64-Bit Server VM 16.0.1+9) Host: Windows 10 10.0 (amd64)

**Additional context**
https://hastebin.com/uniqumiveg.properties

https://paste.ubuntu.com/p/qd9M7jk9tg/

**Comment by Steel-Dev** [comment]
I'm unable to recreate this issue. Can you provide any more information?

**Comment by FunkyNico** [comment]
Plugins (53): AngelChest, AuctionMaster, AureliumSkills, AuthMe, BetterNetherite, BloodNight, Bookshelf, ChestSort, Chunky, ChunkyBorder, CombatLogX, CoreProtect, CrashAPI, DragonSlayer, Elevator, EnchantGui, EnchantmentSolution, Essentials, EssentialsChat, EssentialsSpawn, eZProtector, FarmControl, FartherViewDistance, FastAsyncWorldEdit (WorldEdit), FastLogin, Harbor, IllegalStack, Insights, InvSeePlusPlus, LevelledMobs, LuckPerms, LWC, MoneyHunters, Monstrorvm, Multiverse-Core, NexEngine, Oh_the_dungeons_youll_go, PaintballBattle, PlaceholderAPI, ProtectionStones, ProtocolLib, RepairGui, RHLeafDecay, SirBlobmanCore (SirBlobmanAPI, XSeries), SkinsRestorer, Skulls, spark, SuperChairs, Terra, Vault, Vulcan, WorldEditSelectionVisualizer, WorldGuard

Another log: https://hastebin.com/ovaxecayuv.sql / https://paste.ubuntu.com/p/N7VkMCM7Sj/

**Comment by Steel-Dev** [comment]
Can you show me the configuration file?

**Comment by Steel-Dev** [comment]
It could be the plugin you have for logins messing with it.

**Comment by FunkyNico** [comment]
Config,yml: https://hastebin.com/jerecucuqo.yaml / https://paste.ubuntu.com/p/Jf7q6zhnjj/

Login plugin: https://www.spigotmc.org/resources/authmereloaded.6269/
Fastlogin: https://www.spigotmc.org/resources/fastlogin.14153/

**Comment by Steel-Dev** [comment]
The issue is in the config, you put `%l` in the prefix.

![image](https://user-images.githubusercontent.com/12509016/127259067-17a2957a-a452-434d-a08e-4c141b179e81.png)

It's trying to format %l to something, but %l isnt a valid format option, hence creating the error.

Did you meant to put &l?

**Comment by FunkyNico** [comment]
It was that lol. Thanks.
